codecov:
  allow_coverage_offsets: true  # Avoid "Missing base report" due to committing with "[CI skip]"

comment:
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        threshold: 0.1%
